name: Automerge Dependabot

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Auto Approve
      if: steps.cpr.outputs.pull-request-operation == 'created'
      run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Automerge Pull Request
      if: steps.cpr.outputs.pull-request-operation == 'created'
      run: gh pr merge --merge --auto "1"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
