name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run Mirror
      run: |
        npm install
        npm run mirror
        git status
    - name: Open Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ GITHUB_TOKEN }}
    - name: Automerge Pull Request
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ GITHUB_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash
